name: lms_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.5+17

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.12
  firebase_messaging: ^15.2.5
  flutter_rating_bar: ^4.0.1
  last_pod_player: ^0.0.6
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.3
  flutter_html: ^3.0.0-beta.2
  easy_localization: ^3.0.5
  hive_flutter: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  flutter_riverpod: ^2.5.1
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  line_icons: ^2.0.3
  feather_icons: ^1.2.0
  cached_network_image: ^3.4.1
  simple_animations: ^5.0.2
  font_awesome_flutter: ^10.7.0
  flutter_web_browser: ^0.17.1
  quiver: ^3.2.1
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  firebase_storage: ^12.4.5
  material_dialogs: ^1.1.4
  device_info_plus: ^9.1.2
  path_provider: ^2.1.2
  app_settings: ^6.1.1
  loading_indicator: ^3.1.1
  smooth_page_indicator: ^1.1.0
  store_redirect: ^2.0.3
  shimmer: ^3.0.0
  google_mobile_ads: ^6.0.0
  html_unescape: ^2.0.0
  share_plus: ^11.0.0
  firebase_analytics: ^11.4.5
  screen_protector: ^1.4.2+1
  rounded_loading_button_plus: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21




flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/animations/
   - assets/images/
   - assets/translations/
        


    
